const SHOP_DATA = [
  {
    name: "Fire Emblem Engage - Nintendo Switch, Nintendo Switch (OLED Model), Nintendo Switch Lite",
    shortname: "Fire Emblem Engage",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 59.99,
    onSale: false,
    rating: 5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },
  {
    name: "Nintendo - Switch – OLED Model w/ White Joy-Con - White",
    shortname: "Nintendo Switch",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 349.99,
    onSale: false,
    rating: 5,
    inStock: true,
    categories: ["Consoles", "Nintendo Switch"],
  },
  {
    name: "Sony - PlayStation 5 Console",
    shortname: "Sony Playstation 5",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 499.99,
    onSale: false,
    rating: 5,
    inStock: false,
    categories: ["Consoles", "Playstation 5"],
  },
  {
    name: "Logitech - G203 LIGHTSYNC Wired Optical Gaming Mouse with 8,000 DPI sensor - Black",
    shortname: "Logitech Wired Gaming Mouse",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 37,
    oprice: 50,
    onSale: true,
    rating: 3,
    inStock: false,
    categories: ["Accessories", "PC"],
  },
  {
    name: "Pokémon Scarlet - Nintendo Switch, Nintendo Switch – OLED Model, Nintendo Switch Lite",
    shortname: "Pokemon Scarlet",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 59.99,
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },
  {
    name: "Pokémon Violet - Nintendo Switch, Nintendo Switch – OLED Model, Nintendo Switch Lite",
    shortname: "Pokemon Violet",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 59.99,
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },
  {
    name: "Microsoft - Xbox Series X 1TB Console - Black",
    shortname: "Xbox Series X",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 499.99,
    onSale: false,
    rating: 5,
    inStock: false,
    categories: ["Consoles", "Xbox"],
  },
  {
    name: "The Last of Us Part I - PlayStation 5",
    shortname: "The Last of Us",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 5,
    inStock: false,
    categories: ["Games", "Playstation 5"],
  },
  {
    name: "Resident Evil 4 Standard Edition - PlayStation 5",
    shortname: "Resident Evil 4",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 59.99,
    onSale: false,
    rating: 5,
    inStock: true,
    categories: ["Games", "Playstation 5"],
  },
  {
    name: "Resident Evil 4 Standard Edition - Xbox Series X",
    shortname: "Resident Evil 4",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 42.99,
    oprice: 59.99,
    onSale: true,
    rating: 5,
    inStock: true,
    categories: ["Games", "Xbox"],
  },
  {
    name: "Marvel's Spider-Man 2 Launch Edition - PlayStation 5",
    shortname: "Marvel's Spider-Man 2",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 5,
    inStock: true,
    categories: ["Games", "Playstation 5"],
  },
  {
    name: "Call of Duty: Modern Warfare III Cross-Gen Bundle Edition - Xbox Series X, Xbox One",
    shortname: "Call of Duty: Modern Warfare III",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 3,
    inStock: true,
    categories: ["Games", "Xbox"],
  },
  {
    name: "Call of Duty: Modern Warfare III Standard Edition - PlayStation 5",
    shortname: "Call of Duty: Modern Warfare III",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 4,
    inStock: true,
    categories: ["Games", "Playstation 5"],
  },
  {
    name: "The Legend of Zelda: Tears of the Kingdom Standard Edition - Nintendo Switch, Nintendo Switch – OLED Model, Nintendo Switch Lite",
    shortname: "The Legend of Zelda: Tears of the Kingdom",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },
  {
    name: "Madden NFL 24 Standard Edition - Xbox Series X, Xbox One",
    shortname: "Madden NFL 24",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Xbox"],
  },
  {
    name: "Final Fantasy XVI Standard Edition - PlayStation 5",
    shortname: "Final Fantasy XVI",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Playstation 5"],
  },
  {
    name: "Dead Space - PlayStation 5",
    shortname: "Dead Space",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 5,
    inStock: false,
    categories: ["Games", "Playstation 5"],
  },
  {
    name: "Star Wars Jedi: Survivor Standard Edition - Xbox Series X",
    shortname: "Star Wars Jedi: Survivor",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 69.99,
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Xbox"],
  },
  {
    name: "Super Mario Bros. Wonder - Nintendo Switch, Nintendo Switch – OLED Model, Nintendo Switch Lite",
    shortname: "Super Mario Bros. Wonder",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 59.99,
    onSale: false,
    rating: 5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },
  {
    name: "Sony - PlayStation 5 - DualSense Wireless Controller - White",
    shortname: "Ps5 - Wireless Controller",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 49.99,
    oprice: 69.99,
    onSale: true,
    rating: 5,
    inStock: true,
    categories: ["Accessories", "Playstation 5"],
  },
  {
    name: "HP OMEN - 27 IPS LED QHD 240Hz FreeSync and G-SYNC Compatible Gaming Monitor with HDR (DisplayPort, HDMI, USB) - Black",
    shortname: "HP OMEN Monitor",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 299.99,
    oprice: 429.99,
    onSale: true,
    rating: 5,
    inStock: true,
    categories: ["PC"],
  },
  {
    name: "Dell - S2721HGF 27 Gaming - LED Curved FHD FreeSync and G-SYNC Compatible Monitor (DisplayPort, HDMI) - Black",
    shortname: "Dell S2721HGF Gaming Monitor",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 149.99,
    oprice: 259.99,
    onSale: true,
    rating: 5,
    inStock: true,
    categories: ["PC"],
  },
  {
    name: "Mario Kart 8 Deluxe - Nintendo Switch",
    shortname: "Mario Kart 8 Deluxe",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 48.99,
    oprice: 59.99,
    onSale: true,
    rating: 5,
    inStock: true,
    categories: ["Games", "Nintendo Switch"],
  },
  {
    name: "Forza Horizon 5 Standard Edition - Xbox One, Xbox Series X",
    shortname: "Forza Horizon 5 Standard Edition",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 47.99,
    oprice: 59.99,
    onSale: true,
    rating: 5,
    inStock: true,
    categories: ["Games", "Xbox"],
  },
  {
    name: "SteelSeries - Arctis 9 Wireless Gaming Headset for PC, PS5, and PS4 - Black",
    shortname: "SteelSeries Wireless Headset",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 99.99,
    oprice: 199.99,
    onSale: true,
    rating: 4,
    inStock: true,
    categories: ["Accessories", "Playstation 5", "PC"],
  },
  {
    name: "Nintendo - Nintendo 64 Console",
    shortname: "Nintendo 64",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 129.99,
    onSale: false,
    rating: 4,
    inStock: false,
    categories: ["Consoles", "Retro"],
  },
  {
    name: "Sony - PlayStation 2 Console",
    shortname: "PlayStation 2",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 129.99,
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Consoles", "Retro"],
  },
  {
    name: "Nintendo - Nintendo 3DS",
    shortname: "Nintendo 3DS",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 99.99,
    onSale: false,
    rating: 4.5,
    inStock: true,
    categories: ["Consoles", "Handheld", "Retro"],
  },
  {
    name: "ASUS - ROG Ally 7 120Hz FHD 1080p Gaming Handheld - AMD Ryzen Z1 Extreme Processor - 512GB - White",
    shortname: "Asus Gaming Handheld",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 619.99,
    oprice: 699.99,
    onSale: true,
    rating: 4.5,
    inStock: true,
    categories: ["Consoles", "Handheld"],
  },
  {
    name: "Street Fighter 6 Standard Edition - Xbox Series X",
    shortname: "Street Fighter 6",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 45.99,
    oprice: 59.99,
    onSale: true,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Xbox"],
  },
  {
    name: "Grand Theft Auto V Premium Edition - PlayStation 4, PlayStation 5",
    shortname: "Grand Theft Auto V",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 20.99,
    oprice: 29.99,
    onSale: true,
    rating: 4.5,
    inStock: true,
    categories: ["Games", "Playstation 5"],
  },
];

export default SHOP_DATA;
