const SHOP_DATA = [
  {
    name: "MacBook Pro 16 Laptop - Apple M1 Pro chip - 16GB Memory - 1TB SSD - Space Gray",
    shortname: "MacBook Pro 16 Laptop",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 2699,
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    name: "Fire Emblem Engage - Nintendo Switch, Nintendo Switch (OLED Model), Nintendo Switch Lite",
    shortname: "Fire Emblem Engage",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 59.99,
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    name: "Nintendo - Switch – OLED Model w/ White Joy-Con - White",
    shortname: "Nintendo Switch",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 349.99,
    percentOff: "",
    rating: 5,
    inStock: true,
  },
  {
    name: "CORSAIR - VENGEANCE PRO 32GB (2PK x 16GB) 3600MHz DDR4 C18 DIMM Desktop Memory with RGB lighting",
    shortname: "Corsair Vengeance Pro 32GB",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 89.99,
    oprice: 99.99,
    percentOff: 10,
    rating: 4.5,
    inStock: true,
  },
  {
    name: "Sony - PlayStation 5 Console",
    shortname: "Sony Playstation 5",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: "",
    oprice: 499.99,
    percentOff: "",
    rating: 5,
    inStock: false,
  },

  {
    name: "AMD - Ryzen 7 5800X 4th Gen 8-core, 16-threads Unlocked Desktop Processor Without Cooler",
    shortname: "AMD Ryzen 7 5800X",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 249,
    oprice: 449,
    percentOff: 45,
    rating: 4.5,
    inStock: true,
  },
  {
    name: "Logitech - G203 LIGHTSYNC Wired Optical Gaming Mouse with 8,000 DPI sensor - Black",
    shortname: "Logitech Wired Gaming Mouse",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque culpa, odio, qui praesentium dignissimos eaque dolorum porro alias neque, eius animi ipsa voluptates. Optio repellat tempora voluptas, dolores ipsam ad!",
    img: "",
    dprice: 37,
    oprice: 50,
    percentOff: 25,
    rating: 3,
    inStock: false,
  },
];

export default SHOP_DATA;
